### ISSUE TITLE
Any Plans for Digital Ocean?

### ISSUE THREAD

**Issue by nautis** [konstk1/helium-dashboard#1]
AWS can get a little complicated. Any plans for implementing for Digital Ocean?

**Comment by konstk1** [comment]
There's very little that's specific to AWS here. Just the handler in index.js. If Digital Ocean has an equivalent of Lambda, it's easy to modify. If you're talking about running it on a VM, then just set it up as a corn job and run with `npm start`.

**Comment by nautis** [comment]
I will try that. Thanks!
