### ISSUE TITLE
Beacon sent/received clarification

### ISSUE THREAD

**Issue by ThomDietrich** [konstk1/helium-dashboard#10]
Hey there,
working with first collected data, I am a bit confused by the following:

https://github.com/konstk1/helium-dashboard/blob/5701e0cd342b1214041ffd370f91868165373423/src/helium.js#L81-L85

If my hotspot is the one that was challenged, we say that a beacon was sent, otherwise received. Isn't it the other way around? 

This element from the explorer is translated to "beacon received":

![image](https://user-images.githubusercontent.com/2870104/160215914-30bd89f6-51f8-42a9-ab69-1e9c2932adbe.png)

**Comment by konstk1** [comment]
Challenged Beaconer is different from sent Beacon. Sent Beacon is when you're being challenged. Here's an example: https://explorer.helium.com/txns/TtdhatBTZ9mjJCKONPEEbqGxydm_e4ZCD8xnSAT6EVI

**Comment by ThomDietrich** [comment]
Exactly. In the example my hotspot challenged another hotspot to broadcast a beacon. This is not "beacon received"?

**Comment by konstk1** [comment]
No, when you're being challenged, you're being asked to send a beacon. The way it works is a challenger generates a challenge and is sent to the chalangee. The challengee then broadcasts/sends a beacon to be witnessed by others. So if you're the challengee, you're sending a beacon.

**Comment by ThomDietrich** [comment]
Exactly. This is pretty basic knowledge. So even though you agree it's "sending a beacon", why is this event captured in influxdb with the tag "beacon received"?

**Comment by konstk1** [comment]
It's not. If I'm the challengee, I'm sending the beacon and it's being tagged as 'beacon_sent'. What am I missing?

```
if (act.path[0].challengee == process.env.HELIUM_HOTSPOT) { 
   point.tag('type', 'beacon_sent'); 
   // console.log('Beacon sent: witnesses ', act.path[0].witnesses.length); 
 }
```

**Comment by ThomDietrich** [comment]
All clear now. It was late and the naming of your fields/tags might have been confusing. 

- Field `witnesses` + Tag `beacon_sent` = Number of witnesses of the hotspot's beacon, important
- Field `witnesses` + Tag `beacon_received` = Number of witnesses of beacons my hotspot witnessed, not really important (in fact its only use in the Grafana dashboard is better covered by the field `count`). Anyhow, I won't complain about extra data.

Issue resolved
