### ISSUE TITLE
Random Data in Dashboard?

### ISSUE THREAD

**Issue by Elliot1423** [konstk1/helium-dashboard#11]
Hey,

Not sure what I am doing wrong, I have followed the guide, everything setup, syncing of data into Influx working well, can see the data in the DB, I have edited the grafana helium_dashboard.json file with the ID of my hotspot and imported but I am getting random data appearing, see pics attached, every time I refresh the dashboard completely different figures show, seems to be random/gibberish?  I can't seem to work out how the dashboard is pulling data from Influx, just seems to point at the API? 

Have I missed a step? 

Many Thanks

Elliot

![Screenshot 2022-03-31 at 22 56 03](https://user-images.githubusercontent.com/102767846/161155931-8a8eaa0f-da0e-4644-9aeb-a9bc888748d4.png)
![Screenshot 2022-03-31 at 22 56 18](https://user-images.githubusercontent.com/102767846/161155936-3fab9f82-dae2-4697-badd-e2f8226f48bd.png)

**Comment by Elliot1423** [comment]
So with some more playing, I assumed a connection needed setting up in Grafana to point to Influx, not in the instructions but thought I'd give it a go a voila

https://docs.influxdata.com/influxdb/v2.0/tools/grafana/#view-and-create-influxdb-dbrp-mappings

Good link for anyone else having this issue :)

**Comment by konstk1** [comment]
I'll happily take a PR if you'd like to update the instructions based on your recent experience.
