### ISSUE TITLE
Add an Open Source License

### ISSUE THREAD

**Issue by ThomDietrich** [konstk1/helium-dashboard#12]
Hey @konstk1,
thanks your this project! It's doing great for me. I would love to offer my improvements back to you, if you are interested.
Before that, would you care to select a license you want this repo be under? Thanks!!
https://choosealicense.com/

**Comment by konstk1** [comment]
Done

**Comment by ThomDietrich** [comment]
Thanks.
Plese have a look at my repo. I ended up with a complete redesign of the database structure and the grafana dashboard.
If you want to have a look remember that you can actually pull all historic hotspot activity from the blockchain API
