### ISSUE TITLE
I get a error massage if i start the script . Please help

### ISSUE THREAD

**Issue by Leilei0106** [konstk1/helium-dashboard#14]
When i start the script i get this message . Do you have any Idea whats wrong ?  Other Question is it possible to run this Script in IOBroker ? Thx for your help . Regards Daniel

Execution at Wed May 18 2022 21:31:43 GMT+0000 (Coordinated Universal Time)
Processing helium
Helium: collecting network stats
Helium: price: { helium: { usd: 8.03 } }
Helium: rejected
  -> Error:  Request failed with status code 404
Error:  Request failed with status code 404

**Comment by konstk1** [comment]
Did you set up your .env file correctly?

**Comment by Leilei0106** [comment]
I change the .env.sample file to .env with this settings. In the Influx dp it push allready the HNT Price , ( sounds for me the Connection between data server and Influx db work. Now it works in the Docker . How do it work on A linux environment? would be easyer for me on the Proxmox Linux VM.  Is it possible for you to explaine in witch Folder Structure i should copy your files . Is there anythink else to change in the scrips beside the .env file ? After that to run the script only "npm start" and it should run the Cron Job on the Linux right ? 
. Thanks for your patience . Lg Daniel 

Thats my Helium Hotspot settings in the .env file

HELIUM_WALLET  = 14dsdn58FkvzQi3oqjs6uz83zU4PYTCMxE2K7kyZe8WkwnnLsZM
HELIUM_HOTSPOT = Beautiful-Misty-Hare,Genuine-Sangria-Snail

**Comment by konstk1** [comment]
HELIUM_HOTSPOT must be the hotspot identifier (similar format as the wallet), not the name.

**Comment by Leilei0106** [comment]
Thx it work now in the Docker Image on my Synology ;) Sometimes i get error massages but i think its the Helium network. The cron job sould run after a reboot or i need to enter the "npm start"  Regards

**Comment by konstk1** [comment]
The cron should start on boot.

**Comment by dqcenter** [comment]
> Thx it work now in the Docker Image on my Synology ;) Sometimes i get error massages but i think its the Helium network. The cron job sould run after a reboot or i need to enter the "npm start" Regards

Hi there, can you share your docker compose file? Thanks
