### ISSUE TITLE
404's on retrieving hotspots by name

### ISSUE THREAD

**Issue by Kronoc123** [konstk1/helium-dashboard#3]
Hey there, thanks for building this! I'm just looking at modifying for my needs and this is an amazing intro to the helium http js SDK.

I've noticed on my machine that I always get a 404 whenever retrieving a hotspot by name is run. ie
```
let hotspot = await helium.hotspots.get(process.env.HELIUM_HOTSPOT);
```

![image](https://user-images.githubusercontent.com/97264137/149608019-50d72f54-f488-41a0-92a1-6d7feda3d04a.png)

I've validated that `process.env.HELIUM_HOTSPOT` resolves to the name in my .env file. And also just changing to other names also result in a 404.

Updated to 3.60.0 of the helium/http library, but no dice.

Any ideas?

**Comment by Kronoc123** [comment]
Found the issue, not sure when it was introduced/broken. But when capturing the traffic in Fiddler I noticed it was hitting the wrong path on the helium API.

Requests are going to ``api.helium.io/v1/hotspots/<hotspotname>`` whereas they should have been 
``api.helium.io/v1/hotspots/name/<hotspotname>``, see Fiddler trace below

![image](https://user-images.githubusercontent.com/97264137/149612555-e73b4b06-b66d-407a-b567-f5a47049c787.png)

So changing to append ``name/``<hotspotname> in the hotspot get request in helium.js:
![image](https://user-images.githubusercontent.com/97264137/149612545-5997fdf7-ae4d-4aec-b7f1-517623a22026.png)

Now sends requests to the right path (ignore 502 error)
![image](https://user-images.githubusercontent.com/97264137/149612661-f7c6d770-152f-478e-a7fc-8b1ad1975ec2.png)

and runs successfully!
![image](https://user-images.githubusercontent.com/97264137/149612827-0facdf5f-10a6-42d9-af5c-d6c73c6f9019.png)

**Comment by Kronoc123** [comment]
okay next issue is when requesting activities nothing is returned...fml, giving up on this library

![image](https://user-images.githubusercontent.com/97264137/149613748-e57c81fe-cd2f-430d-958c-50d2a946d29d.png)

**Comment by Kronoc123** [comment]
ugh, just found the other issue lol #2, 

For anyone else, line 39 in helium.js should be

![image](https://user-images.githubusercontent.com/97264137/149613966-77b21a5b-25a4-4277-9138-1d44166c35af.png)

**Comment by nevrrmind** [comment]
> ugh, just found the other issue lol #2,
> 
> For anyone else, line 39 in helium.js should be
> 
> ![image](https://user-images.githubusercontent.com/97264137/149613966-77b21a5b-25a4-4277-9138-1d44166c35af.png)

Changing Line 39 to `let hotspot = await helium.hotspots.get(process.env.HELIUM_WALLET);` will result in "Error:  Request failed with status code 404"

Just leave it `let hotspot = await helium.hotspots.get(process.env.HELIUM_HOTSPOT);` and it will be fine!

**Comment by Kronoc123** [comment]
> > ugh, just found the other issue lol #2,
> > For anyone else, line 39 in helium.js should be
> > ![image](https://user-images.githubusercontent.com/97264137/149613966-77b21a5b-25a4-4277-9138-1d44166c35af.png)
> 
> Changing Line 39 to `let hotspot = await helium.hotspots.get(process.env.HELIUM_WALLET);` will result in "Error: Request failed with status code 404"
> 
> Just leave it `let hotspot = await helium.hotspots.get(process.env.HELIUM_HOTSPOT);` and it will be fine!

That doesn't work for me, as mentioned above.

There's two ways to retrieve the hotspot info, by `` hotspot name`` or by ``hotspot address``:

![image](https://user-images.githubusercontent.com/97264137/150609843-0970e176-253e-4f5e-822d-54744750eb24.png)

but via the helium JS http library there's no method to pass just the ``hotspot name``

helium.hotspots.get(``HOTSPOT_ADDRESS_HERE``)
helium.hotspots.fromAddress(``HOTSPOT_ADDRESS_HERE``)

I don't see a way to pass it the ``hotspot name`` and actually get returned data?!

![image](https://user-images.githubusercontent.com/97264137/150610103-ba4d54a1-0363-4317-ac31-1c14aa641d2f.png)

**Comment by konstk1** [comment]
@Kronoc123, I don't think names were ever meant to be used as identifiers. Everything in the API works based on the hotspot address, not the name. You should adapt your design to do the same.

**Comment by Kronoc123** [comment]
> @Kronoc123, I don't think names were ever meant to be used as identifiers. Everything in the API works based on the hotspot address, not the name. You should adapt your design to do the same.

Yep agreed fully, and I have fixed my issue, hence above comments and closing this issue. 
I mistakenly thought that HELIUM_HOTSPOT was the hotspot name, rather than it's id

![image](https://user-images.githubusercontent.com/97264137/150616297-3c5060e5-1e67-42cf-a1cb-7c97df34795e.png)
