### ISSUE TITLE
How to Install ??

### ISSUE THREAD

**Issue by bug84** [konstk1/helium-dashboard#6]
I have import the helium_dashboard.json to my grafana with influx. i have editing the file with my hotspot id. 

in grafana shows me NO DATA in all tables. what i have made wrong?

**Comment by konstk1** [comment]
How are you pushing the data into influx?

**Comment by bug84** [comment]
i have a docker instance of grafana and influx.
influx is connected as data source in grafana.
installed successfull the plugin in grafana with terminal.

how to push the data in influx?

**Comment by konstk1** [comment]
Sounds like an SSL/connection issue with your influx setup. This is outside the scope. Closing this issue.

**Comment by ideasman69** [comment]
hi @bug84 - just edit the ./src/influx.js to remove the s from https and it'll work with a stock non-https install of influx

**Comment by bug84** [comment]
> influx.js

thank you. but i cant find this file in my docker container...

**Comment by bug84** [comment]
> hi @bug84 - just edit the ./src/influx.js to remove the s from https and it'll work with a stock non-https install of influx

thats it, it work.
thank you very much
