### ISSUE TITLE
possible to run in a docker?

### ISSUE THREAD

**Issue by ideasman69** [konstk1/helium-dashboard#7]
Hi there,

This dash looks great and I'm keen to give it a go but I've been struggling to get the node.js part running in a docker. The influx + grafana dockers are up and running, but missing the vital piece of populating the data.

There's a [aws-lambda-nodejs](https://hub.docker.com/r/amazon/aws-lambda-nodejs) docker available but after hours of trying I'm getting nowhere. 

I understand if it's out of scope for help but a gentle push in the right direction (website / guide / etc) would be greatly appreciated.

Cheers!

**Comment by konstk1** [comment]
Why not just run it on AWS?
